:scrollbar:
:data-uri:
:toc2:
:linkattrs:

= SSDA App Services Demo Base Checklist
:numbered:

== Purpose

The purpose of this guide is to provide a checklist of base technologies and best practices for the creation of reproducible demos that showcase the Red Hat Application Services portfolio.

These demos should highlight the use of Red Hat Application Services technologies to implement a typical line-of-business (LoB) scenario. 
These demos  should be easy to provision by other Red Hat solution architects or partner system integrators.

The target audience of this guide is developers tasked with contributing to these LoB demos.

The base technologies and best practices listed in this document are common to all demos targeting a line-of-business audience.

In addition to the base technologies listed in this document, there almost certainly will be need for technologies from one or more of Red Hat's three Application Services bundles:

. *Runtimes*
+
Data Grid, Serverless, Service Mesh, Code Ready Workspaces, Tekton/Jenkins

. *Integration*
+
AMQ Streams, Debezium, AMQ Broker, 3scale, Fuse, Camel-K, Fuse Online, Service Registry

. *Business Automation*
+
RH-PAM, RH-DM, Business Optaplanner, Kogito, Dashbuilder

In addition to these Application Services technologies, it may be desirable to include ops monitoring capabilities in your demo. ie:  Prometheus, Grafana, Kabana.

== Base Technologies

=== Local Dev Environment

In order to facilitate a rapid development & testing cycle, you'll need an appropriate local dev environment.

==== Hardware Resources

Modern demos are written using a microservice architecture.
The aggregate amount of hardware to support development of these microservice architected demos tends to be larger than legacy monolith architectures.

.. RAM:   32GBs
.. CPU:   8 threads

==== Tooling

. *Operating System*
+
Your local dev environment needs to run a recent version of one of the following operating systems: 

.. RHEL (preferred)
.. Fedora (preferred)
.. OSX

. *git*
. *Java*
.. Ensure your local dev environment is enabled with OpenJDK 11 (or more recent)
.. maven
+
You'll need working experience creating java projects that reference the Red Hat GA supported libraries at link:https://maven.repository.redhat.com/ga/[maven.repository.redhat.com]

.. IDE:  VSCode ( enabled with the link:https://marketplace.visualstudio.com/items?itemName=redhat.java[Language Support for Java extension] by Red Hat ) is recommended.

. *podman*
. *buildah*
. *docker-compose*
+
Locally demo development can be greatly facilitated by managing supporting database, messaging and security infrastructure via a _docker-compose_ file.
+
The _docker-compose_ utility can be run on Fedora / RHEL as a facade to underlying podman functionality as per this link:https://fedoramagazine.org/use-docker-compose-with-podman-to-orchestrate-containers-on-fedora/[tutorial].

. *oc utility*
+
All versions of this utility are available at either of the following:

.. https://access.redhat.com/downloads/content/290
+
RHN subscription required

.. https://mirror.openshift.com/pub/openshift-v4/clients/ocp/?C=M;O=D
+
Accessible without a RHN subscription

. *ansible*
+
ie: dnf install ansible

=== Repositories

. Source Code:  link:https://github.com/redhat-naps-da[Red Hat Government Strategic Solutions Github Organization]

. Container images: link:https://quay.io/organization/redhat_naps_da[Red Hat NAPS DA Quay Organization]

=== Red Hat Single Sign-On

The vast majority of demos targeting a line-of-business audience will speak to different personas with different roles and user attributes.
As such, your demo should make use of the OpenID Connect protocol.

You should be well-versed in the use of Red Hat SSO as the OpenID Connect _Identity Provider_ for your demo.

In particular, the following is a checklist of RH-SSO capabilities that are often utilized to facilitate demos:

. *SSO Realm*
+
An entire SSO realm should be version controlled in git and loaded into RH-SSO during provisioning of the demo.  During an un-install, that SSO Realm should be deleted from RH-SSO.

. *SSO Client(s)*
+
At least one SSO Client will need to be created and most likely enabled for OIDC's _Authorization Code Flow_ (to issue JWT access tokens).
+
The client should also be properly configured with client re-directs and CORS.

. *Users & Roles*
+
You'll want to think through the users and roles needed to facilitate the business scenario of your demo.  These users and roles should be included in the JSON representation of your SSO Realm.  

. *User Attributes*
+
You'll want to think through the user attributes that should be included in the access token of an authenticated user.  These attributes for each user should also be included in the JSON representation of your SSO Realm.

=== Quarkus

The default programming language for all services of a demo should be Quarkus.

The use of the SmallRye Mutiny reactive libraries is highly recommended.

RESTful APIs should include OpenAPI documentation by default by including the following quarkus dependency:  io.quarkus:quarkus-smallrye-openapi

To facilitate deployment and health-check needs, the following Quarkus plugins are highly recommended:

. *quarkus-container-image-docker*
. *quarkus-smallrye-health*

Related, at deployment time, add a custom application.properties to a configmap and bind to the following directory of the pod:  /deployments/config/application.properties.

Compilation to a native binary (ie: Mandrel) is a capability that can be discussed (if/when appropriate) during a presentation but is not typically needed for the LoB targetted demo itself.

=== RDBMS

PostgreSQL tends to be the default RDBMS that serves many of Red Hat's Application Services technologies. ie:  RH-SSO, Kogito, Fuse Online, etc.

As such, it is recommended that where there is additional need for a RDBMS to support your demo, PostgreSQL be used.

During the presentation, if/when asked about production considerations of an RDBMS, remind the audience that Red Hat is not a database company and elaborate on the many production options available on the market.

=== OpenShift

Default target platform for all business focused demos is OpenShift.

It's likely that your demo should be deployed to the Valkyrie cluster.
It's possible that your demo should also be made available via RHPDS.

Ensure that all Deployments or Deployment Configs define a limits and requests as well as health checks.

Assume that your demo could be deployed into an OpenShift environment where the Openshift administrator has imposed a Quota and LimitRange on your demo.
As part of the demo source control, it is recommended that a sample Quota and LimitRange configs be included.

Do not assume that the routes exposed by the target OpenShift cluster that your demo will ultimately be deployed to are secured using a certificate signed by a known Certificate Authority (ie:  Lets Encrypt)

=== Storage

For the purpose of your demo targetting a line-of-business audience, keep storage requirements simple.

Stick to the use of RWO persistent volumes.

==== Operator Lifecycle Manager

Provisioning of infrastructure related coomponents such AMQ Streams, RH-SSO, Serverless, etc should be via the Operator Lifecycle Manager (OLM).

=== Ansible

An ansible playbook should be authored to deploy your complete application to OpenShift in a repeatable manner.


=== Asciidoc / Markdown

Write your documentation in either asciidoc or markdown and version control it as part of the demo's git project.

Please include of table of contents.  Major sections of the documentation should include the following: 

. Purpose
. Provisioning instructions
. Architecture diagram
. Demo script
+
ie:  details and screenshots illustrating how to run the demo for a customer

. Technical discussion vectors
+
List of possible discussion vectors with a customer that the demo could inspire  

=== Web Apps

A demo tailored toward a line of business audience will need one or more user interfaces.

These user interfaces should be written in either Angular or ReactJS.

The use of Patternfly is also recommended.

These user interfaces should be reactive n the sense that they consume events via either websockets or Server Sent Events (SSE).

Note that the HA-Proxy router of OpenShift kills persistent TCP connection (ie:  SSE, Websockets, etc) every 30 seconds (by default).
Make sure that the SSE or websocket clients in your UI can gracefully recover.

== Out of Scope

. *Email*
+
Emails are often a nice addition to line-of-business related demos.  
Unfortunately, there is not a zero-cost smtp service that can be leveraged reliably in a hands-off automated manner.
+
When SMTP is needed, _free-tier_ services such as SocketLabs and SendGrid can be leveraged on a case by case basis by the SA responsible for delivering the demo to their customer.
+
If/when a SMTP service is needed, the demo documentation should provide guidence on the integration touchpoints.

. *CI/CD*
+
CI/CD is certainly important for the evolution of any software solution.
However, for the purpose of a demo targetting a line-of-business audience, its typically sufficient to simply discuss CI/CD considerations as part of a presentation.

== Advanced

=== Ansible Operator SDK

To facilitate the availability of your demo, the link:https://sdk.operatorframework.io/docs/building-operators/ansible/tutorial/[Ansible Operator SDK] can be used to create an Operator from the demo ansible you've already created.

=== Agnosticd

It might make sense to make your demo available to Red Hatters and partners via RHPDS.


This can be done by creating an ansible role in link:https://github.com/redhat-cop/agnosticd[Agnosticd].

When an end-user orders your demo from RHPDS, this agnosticd ansible role can pull your operator and install it (and subsequently your demo) on an OpenShift cluster.

== Examples

. link:https://github.com/redhat-naps-da/himss_interoperability_showcase_2021[HIMSS 2021 Demo]
. link:https://www.erdemo.io/[ER-Demo]
