:scrollbar:
:data-uri:
:toc2:
:linkattrs:

= SSDA App Services Demo Creation Checklist
:numbered:

== Purpose

The purpose of this guide is to document a checklist of technologies and best practices for the creation of reproducible demos that showcase the Red Hat Application Services portfolio.

These demos should speak to typical line-of-business scenario and should be easily provisioned by other Red Hat solution architects and/or partner system integrators.

The target audience of this guide are demo developers.

== Base Technologies

=== Local Dev Environment

As a demo author, you'll need an appropriate local dev environment.

==== Hardware Resources

Modern demos are written using a microservice architecture.
The aggregate amount of hardware to support development of these microservice architected demos tends to be larger than legacy monolith architectures.

.. RAM:   32GBs
.. CPU:   8 threads

==== Tooling

. Operating System
+
Your local dev environment needs to run a recent version of one of the following operating systems: 

.. *RHEL* (preferred)
.. *Fedora* (preferred)
.. *OSX*

. git
. Java
.. Ensure your local dev environment is enabled with OpenJDK 11 (or more recent)
.. maven
+
You'll need working experience creating java projects that reference the Red Hat GA supported libraries at link:https://maven.repository.redhat.com/ga/[maven.repository.redhat.com]

.. IDE:  VSCode ( enabled with the link:https://marketplace.visualstudio.com/items?itemName=redhat.java[Language Support for Java extension] by Red Hat ) is recommended.

. *podman*
. *buildah*
. *docker-compose*
+
Locally demo development can be greatly facilitated by managing supporting database, messaging and security infrastructure via a _docker-compose_ file.
+
The _docker-compose_ utility can be run on Fedora / RHEL as a facade to underlying podman functionality as per this link:https://fedoramagazine.org/use-docker-compose-with-podman-to-orchestrate-containers-on-fedora/[tutorial].

. *oc utility*
+
All versions of this utility are available at either of the following:

.. https://access.redhat.com/downloads/content/290
+
RHN subscription required

.. https://mirror.openshift.com/pub/openshift-v4/clients/ocp/?C=M;O=D
+
Accessible without a RHN subscription

. *ansible*
+
ie: dnf install ansible

=== Team Repositories
==== Source Code Version Control

link:https://github.com/redhat-naps-da[Red Hat Government Strategic Solutions Github Organization]

==== Quay

link:https://quay.io/organization/redhat_naps_da[Red Hat NAPS DA Quay Organization]

=== Red Hat Single Sign-On

==== SSO Client(s)

==== Users

==== User Attributes

==== Roles

==== Import Realm JSON

=== Quarkus

=== OpenShift

==== OpenShift Lifecycle Manager

=== Ansible

=== Asciidoc / Markdown


== Advanced

=== Ansible Operator SDK
. link:https://sdk.operatorframework.io/docs/building-operators/ansible/tutorial/[Ansible Operator SDK]

=== Agnosticd
. link:https://github.com/redhat-cop/agnosticd[Agnosticd]

== Examples
