:scrollbar:
:data-uri:
:toc2:
:linkattrs:

= SSDA App Services Demo Creation Checklist
:numbered:

== Purpose

The purpose of this guide is to provide a checklist of technologies and best practices for the creation of reproducible demos that showcase the Red Hat Application Services portfolio.

These demos should highlight the use of Red Hat Application Services technologies to implement a typical line-of-business scenario. 
They should be easily provisioned by other Red Hat solution architects or partner system integrators.

The target audience of this guide are developers tasked with contributing to these demos.

== Base Technologies

=== Local Dev Environment

As a contributor to a demo, you'll need an appropriate local dev environment.

==== Hardware Resources

Modern demos are written using a microservice architecture.
The aggregate amount of hardware to support development of these microservice architected demos tends to be larger than legacy monolith architectures.

.. RAM:   32GBs
.. CPU:   8 threads

==== Tooling

. *Operating System*
+
Your local dev environment needs to run a recent version of one of the following operating systems: 

.. RHEL (preferred)
.. Fedora (preferred)
.. OSX

. *git*
. *Java*
.. Ensure your local dev environment is enabled with OpenJDK 11 (or more recent)
.. maven
+
You'll need working experience creating java projects that reference the Red Hat GA supported libraries at link:https://maven.repository.redhat.com/ga/[maven.repository.redhat.com]

.. IDE:  VSCode ( enabled with the link:https://marketplace.visualstudio.com/items?itemName=redhat.java[Language Support for Java extension] by Red Hat ) is recommended.

. *podman*
. *buildah*
. *docker-compose*
+
Locally demo development can be greatly facilitated by managing supporting database, messaging and security infrastructure via a _docker-compose_ file.
+
The _docker-compose_ utility can be run on Fedora / RHEL as a facade to underlying podman functionality as per this link:https://fedoramagazine.org/use-docker-compose-with-podman-to-orchestrate-containers-on-fedora/[tutorial].

. *oc utility*
+
All versions of this utility are available at either of the following:

.. https://access.redhat.com/downloads/content/290
+
RHN subscription required

.. https://mirror.openshift.com/pub/openshift-v4/clients/ocp/?C=M;O=D
+
Accessible without a RHN subscription

. *ansible*
+
ie: dnf install ansible

=== Repositories

. Source Code:  link:https://github.com/redhat-naps-da[Red Hat Government Strategic Solutions Github Organization]

. Container images: link:https://quay.io/organization/redhat_naps_da[Red Hat NAPS DA Quay Organization]

=== Red Hat Single Sign-On

Every business focused demo should make use of the OpenID Connect protocol.

You should be well-versed in the use of Red Hat SSO as the OpenID Connect _Identity Provider_ for your demo.

In particular, the following is a checklist of RH-SSO capabilities that are often utilized in business focused demos:

. *SSO Realm*
+
An entire SSO realm should be version controlled in git and loaded into RH-SSO during provisioning of the demo.  During an un-install, that SSO Realm should be deleted from RH-SSO.


. *SSO Client(s)*
+
At least one SSO Client will need to be created and most likely enabled for OIDC's _Authorization Code Flow_ (to issue JWT access tokens).
+
The client should also be properly configured with client re-directs and CORS.

. *Users & Roles*
+
You'll want to think through the users and roles needed to facilitate the business scenario of your demo.  These users and roles should be included in the JSON representation of your SSO Realm.  

. *User Attributes*
+
You'll want to think through the user attributes that should be included in the access token of an authenticated user.  These attributes for each user should also be included in the JSON representation of your SSO Realm.

=== Quarkus
The default programming language for all services of a demo should be Quarkus.

From a deployment and runtime perspective, the following Quarkus Plugins are highly recommended:

. *quarkus-container-image-docker*
. *quarkus-smallrye-health*

Related, at deployment time, add a custom application.properties to a configmap and bind to the following directory of the pod:  /deployments/config/application.properties

=== OpenShift

Default target platform for all business focused demos is OpenShift.

It's likely that your demo should be deployed to the Valkyrie cluster.
It's possible that your demo should also be made available via RHPDS.

==== Operator Lifecycle Manager

Provisioning of infrastructure related coomponents such AMQ Streams, RH-SSO, Serverless, etc should be via the Operator Lifecycle Manager (OLM).

=== Ansible

An ansible playbook should be authored to deploy your complete application to OpenShift in a repeatable manner.


=== Asciidoc / Markdown

Write your documentation in either asciidoc or markdown and version control it as part of the demo's git project.

Please include of table of contents.  Major sections of the documentation should include the following: 

. Purpose
. Provisioning instructions
. Architecture diagram
. Demo script
+
ie:  details and screenshots illustrating how to run the demo for a customer

. Technical discussion vectors
+
List of possible discussion vectors with a customer that the demo could inspire  

=== Web Apps

A demo tailored toward a line of business audience will need one or more user interfaces.

These user interfaces should be written in either Angular or ReactJS.

The use of Patternfly is recommended.

These user interfaces should be reactive via either websockets or Server Sent Events (SSE).


== Advanced

=== Ansible Operator SDK

To facilitate the availability of your demo, the link:https://sdk.operatorframework.io/docs/building-operators/ansible/tutorial/[Ansible Operator SDK] can be used to create an Operator from the demo ansible you've already created.

=== Agnosticd

It might make sense to make your demo available to Red Hatters and partners via RHPDS.


This can be done by creating an ansible role in link:https://github.com/redhat-cop/agnosticd[Agnosticd].

When an end-user orders your demo from RHPDS, this agnosticd ansible role can pull your operator and install it (and subsequently your demo) on an OpenShift cluster.

== Examples

. link:https://github.com/redhat-naps-da/himss_interoperability_showcase_2021[HIMSS 2021 Demo]
. link:https://www.erdemo.io/[ER-Demo]
